import { parseImport, type WorkspaceDataset, type Sentiment } from "./model.js";

/** Authored for this demo. None of these statements came from a person or platform. */
interface AuthoredComment {
  id: string;
  product: "AcmeFlow" | "OrbitQuest";
  source: "hackernews" | "youtube" | "lemmy" | "steam";
  thread: string;
  title: string;
  day: number;
  text: string;
  sentiment: Sentiment;
  issues: string[];
  complaint: boolean;
}
const comments: AuthoredComment[] = [
  {
    id: "acme-hn-1",
    product: "AcmeFlow",
    source: "hackernews",
    thread: "acme-team-plans",
    title: "Synthetic discussion: AcmeFlow for a small team",
    day: 3,
    text: "AcmeFlow charged a full seat for each occasional reviewer. Our two editors could not invite six reviewers without doubling the monthly bill.",
    sentiment: "negative",
    issues: ["pricing"],
    complaint: true,
  },
  {
    id: "acme-hn-2",
    product: "AcmeFlow",
    source: "hackernews",
    thread: "acme-team-plans",
    title: "Synthetic discussion: AcmeFlow for a small team",
    day: 4,
    text: "The AcmeFlow setup guide skips the step that maps imported status names. I had to rebuild our board after every item arrived as a draft.",
    sentiment: "negative",
    issues: ["onboarding"],
    complaint: true,
  },
  {
    id: "acme-hn-3",
    product: "AcmeFlow",
    source: "hackernews",
    thread: "acme-team-plans",
    title: "Synthetic discussion: AcmeFlow for a small team",
    day: 5,
    text: "AcmeFlow is not slow on our small boards. The shared review queue saves us a meeting each week, but the price rises sharply when we add guests.",
    sentiment: "mixed",
    issues: ["pricing", "collaboration"],
    complaint: true,
  },
  {
    id: "acme-hn-4",
    product: "AcmeFlow",
    source: "hackernews",
    thread: "acme-team-plans",
    title: "Synthetic discussion: AcmeFlow for a small team",
    day: 6,
    text: "The AcmeFlow guest plan is good value for our agency because every reviewer uses it daily. I would not call that plan expensive for this use.",
    sentiment: "positive",
    issues: ["pricing"],
    complaint: false,
  },
  {
    id: "acme-hn-5",
    product: "AcmeFlow",
    source: "hackernews",
    thread: "acme-api",
    title: "Synthetic discussion: AcmeFlow exports",
    day: 11,
    text: "AcmeFlow exports task names but leaves out the review history. We cannot move a finished project into our archive without copying comments by hand.",
    sentiment: "negative",
    issues: ["export"],
    complaint: true,
  },
  {
    id: "acme-yt-1",
    product: "AcmeFlow",
    source: "youtube",
    thread: "acme-first-board",
    title: "Synthetic tutorial: Build a first AcmeFlow board",
    day: 7,
    text: "The AcmeFlow tutorial uses an older menu. Finding the current import button took longer than importing the actual project.",
    sentiment: "negative",
    issues: ["onboarding"],
    complaint: true,
  },
  {
    id: "acme-yt-2",
    product: "AcmeFlow",
    source: "youtube",
    thread: "acme-first-board",
    title: "Synthetic tutorial: Build a first AcmeFlow board",
    day: 8,
    text: "I followed the AcmeFlow starter checklist and had a working board in ten minutes. The sample project made the roles easy to understand.",
    sentiment: "positive",
    issues: ["onboarding"],
    complaint: false,
  },
  {
    id: "acme-yt-3",
    product: "AcmeFlow",
    source: "youtube",
    thread: "acme-plan-demo",
    title: "Synthetic walkthrough: AcmeFlow plans",
    day: 12,
    text: "The AcmeFlow plan page does not explain whether archived reviewers still need paid seats. I need that answer before I can approve a budget.",
    sentiment: "negative",
    issues: ["pricing"],
    complaint: true,
  },
  {
    id: "acme-yt-4",
    product: "AcmeFlow",
    source: "youtube",
    thread: "acme-plan-demo",
    title: "Synthetic walkthrough: AcmeFlow plans",
    day: 13,
    text: "This synthetic AcmeFlow walkthrough shows the monthly plan, the annual plan, and where the seat counter appears.",
    sentiment: "neutral",
    issues: [],
    complaint: false,
  },
  {
    id: "acme-lemmy-1",
    product: "AcmeFlow",
    source: "lemmy",
    thread: "acme-nonprofit",
    title: "Synthetic discussion: AcmeFlow at a nonprofit",
    day: 14,
    text: "AcmeFlow makes us pay for volunteers who only review one project each month. A limited guest role would fit our nonprofit much better.",
    sentiment: "negative",
    issues: ["pricing"],
    complaint: true,
  },
  {
    id: "acme-lemmy-2",
    product: "AcmeFlow",
    source: "lemmy",
    thread: "acme-nonprofit",
    title: "Synthetic discussion: AcmeFlow at a nonprofit",
    day: 15,
    text: "AcmeFlow support explained our import error in one reply. The corrected file loaded cleanly and the reply included a useful example.",
    sentiment: "positive",
    issues: ["support", "onboarding"],
    complaint: false,
  },
  {
    id: "acme-lemmy-3",
    product: "AcmeFlow",
    source: "lemmy",
    thread: "acme-mobile",
    title: "Synthetic discussion: Mobile review in AcmeFlow",
    day: 18,
    text: "When I review an AcmeFlow card on a narrow screen, the save button moves below the keyboard. I keep closing the keyboard just to save one line.",
    sentiment: "negative",
    issues: ["mobile usability"],
    complaint: true,
  },
  {
    id: "acme-lemmy-4",
    product: "AcmeFlow",
    source: "lemmy",
    thread: "acme-mobile",
    title: "Synthetic discussion: Mobile review in AcmeFlow",
    day: 19,
    text: "I use AcmeFlow on a tablet for weekly reviews. This authored sample has no sentiment label so the demo can show unknown data honestly.",
    sentiment: "unknown",
    issues: [],
    complaint: false,
  },
  {
    id: "orbit-steam-1",
    product: "OrbitQuest",
    source: "steam",
    thread: "orbit-save-reviews",
    title: "Synthetic OrbitQuest player reviews: Save files",
    day: 2,
    text: "OrbitQuest forgot my checkpoint after I changed graphics settings and restarted. I lost the route I had just completed.",
    sentiment: "negative",
    issues: ["save reliability"],
    complaint: true,
  },
  {
    id: "orbit-steam-2",
    product: "OrbitQuest",
    source: "steam",
    thread: "orbit-save-reviews",
    title: "Synthetic OrbitQuest player reviews: Save files",
    day: 5,
    text: "The OrbitQuest autosave icon disappears before the write finishes. Closing the game at that point sent me back to the previous checkpoint.",
    sentiment: "negative",
    issues: ["save reliability"],
    complaint: true,
  },
  {
    id: "orbit-steam-3",
    product: "OrbitQuest",
    source: "steam",
    thread: "orbit-controller-reviews",
    title: "Synthetic OrbitQuest player reviews: Controls",
    day: 9,
    text: "OrbitQuest lets me remap movement, but the map screen still requires the default shoulder button. That breaks my one-handed controller setup.",
    sentiment: "negative",
    issues: ["accessibility", "controls"],
    complaint: true,
  },
  {
    id: "orbit-steam-4",
    product: "OrbitQuest",
    source: "steam",
    thread: "orbit-controller-reviews",
    title: "Synthetic OrbitQuest player reviews: Controls",
    day: 10,
    text: "OrbitQuest combat feels responsive on my controller. The camera sensitivity slider helped me find a comfortable setting.",
    sentiment: "positive",
    issues: ["controls"],
    complaint: false,
  },
  {
    id: "orbit-steam-5",
    product: "OrbitQuest",
    source: "steam",
    thread: "orbit-save-reviews",
    title: "Synthetic OrbitQuest player reviews: Save files",
    day: 16,
    text: "OrbitQuest restored my checkpoint correctly across three restarts. I did not change graphics settings during those sessions.",
    sentiment: "positive",
    issues: ["save reliability"],
    complaint: false,
  },
  {
    id: "orbit-steam-6",
    product: "OrbitQuest",
    source: "steam",
    thread: "orbit-localization",
    title: "Synthetic OrbitQuest player reviews: Subtitles",
    day: 20,
    text: "OrbitQuest subtitles are readable in quiet scenes, but the speaker labels overlap the objective marker during combat.",
    sentiment: "mixed",
    issues: ["accessibility"],
    complaint: true,
  },
  {
    id: "orbit-hn-1",
    product: "OrbitQuest",
    source: "hackernews",
    thread: "orbit-demo",
    title: "Synthetic discussion: OrbitQuest demo",
    day: 8,
    text: "The OrbitQuest demo has a clever navigation puzzle. Each clue teaches a movement skill that the next room asks you to use.",
    sentiment: "positive",
    issues: ["level design"],
    complaint: false,
  },
  {
    id: "orbit-hn-2",
    product: "OrbitQuest",
    source: "hackernews",
    thread: "orbit-demo",
    title: "Synthetic discussion: OrbitQuest demo",
    day: 12,
    text: "OrbitQuest stopped recognizing my remapped confirm button after a cutscene. Opening the settings menu restored it, but that interrupted the puzzle.",
    sentiment: "negative",
    issues: ["controls"],
    complaint: true,
  },
  {
    id: "orbit-hn-3",
    product: "OrbitQuest",
    source: "hackernews",
    thread: "orbit-linux",
    title: "Synthetic discussion: OrbitQuest on Linux",
    day: 17,
    text: "OrbitQuest loaded my saved game on Linux without a problem. This only covers the short demo route, not the full campaign.",
    sentiment: "positive",
    issues: ["save reliability"],
    complaint: false,
  },
];
const parsed = parseImport(
  JSON.stringify(
    comments.map((row) => ({
      organization_id: "synthetic-demo",
      product_id: row.product,
      external_id: row.id,
      source: row.source,
      content: row.text,
      url: null,
      published_at: `2026-09-${String(row.day).padStart(2, "0")}T12:00:00Z`,
      sentiment: row.sentiment,
      relevant: true,
      issue_categories: row.issues,
      is_complaint: row.complaint,
      source_metadata: {
        product_name: row.product,
        thread_id: row.thread,
        thread_title: row.title,
      },
    })),
  ),
  "Authored synthetic feedback",
);
export const sampleDataset: WorkspaceDataset = {
  label: "AcmeFlow and OrbitQuest · synthetic sample",
  provenance: "synthetic",
  records: parsed.records.map((record) => ({
    ...record,
    provenance: "synthetic",
    url: null,
  })),
};
export const sampleDatasets: WorkspaceDataset[] = [
  "AcmeFlow",
  "OrbitQuest",
].map((product) => ({
  label: `${product} · synthetic sample`,
  provenance: "synthetic",
  records: sampleDataset.records.filter((record) => record.product === product),
}));
